#!/bin/bash
filename=~pi/downloads/podcast.txt
TMP=~pi/tmp
cd $TMP
while read -r line
do
    /usr/bin/wget -c "$line"
done < "$filename"
mv $TMP/*mp3 ~pi/videos/mobile
cd -
mv $filename ~pi/documents/past_dl/podcast_`date +'%F_%H.%M.%S'`.txt
