#!/bin/bash
filename=$HOME/downloads/podcast.txt
TMP=$HOME/tmp
cd $TMP
while read -r line
do
    /usr/bin/wget -c "$line"
done < "$filename"
mv $TMP/*mp3 $HOME/videos/mobile
cd -
mv $filename $HOME/documents/past_dl/podcast_`date +'%F_%H.%M.%S'`.txt
