#!/usr/bin/env python
# 1 0 * * * /usr/local/bin/removetorrents.py > $HOME/downloads/log-tr.log 2> $HOME/downloads/error-tr.log
import transmissionrpc

tc = transmissionrpc.Client(address='', port=9091, user='', password='')
torrents = tc.get_torrents()
for torrent in torrents:
  if torrent.status == 'stopped':
    print "Started \"" + torrent.name + "\" (" + str(torrent.totalSize/1000000.0) + " MB). Date Started: " + torrent.date_started.ctime() + ", Date Finished: " + torrent.date_done.ctime()
    tc.start_torrent(torrent.id)
  else:
    print "Torrent \"" + torrent.name + "\" (" + str(torrent.totalSize/1000000.0) + " MB) is in state \"" + torrent.status + "\". Size left: " + str(torrent.leftUntilDone/1000000.0) + " MB."
