#!/usr/bin/env python
# 1 0 * * * /usr/local/bin/starttorrents2.py > $HOME/downloads/log-tr2.log 2> $HOME/downloads/error-tr2.log
from deluge_client import DelugeRPCClient
import time

tc = DelugeRPCClient(host='localhost', port=58846, username='', password='')
tc.connect()
torrents = tc.call('core.get_torrents_status', {}, ['name','state', 'is_finished','total_size','time_added'])
for idtorrent,torrent in torrents.iteritems():
    if torrent['is_finished']:
        print "Torrent \"" + torrent['name'] + "\" (" + str(torrent['total_size']/1000000.0) + " MB) is in state \"" + torrent['state'] + "\"."
    else:
        time_added = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(torrent['time_added']))
        print "Started \"" + torrent['name'] + "\" (" + str(torrent['total_size']/1000000.0) + " MB). Date Started: " + time_added + "."
        tc.call('core.resume_torrent', [idtorrent])
