#!/usr/bin/env python
# 1 0 * * * /usr/local/bin/tr-client 2> /home/pi/downloads/error-tr.log
from subprocess import call
import os
import transmissionrpc
path = r"/home/pi/downloads/tr.txt"
if os.path.isfile(path):
	tc = transmissionrpc.Client(address='localhost', port=9091, user='pi', password='')
	destination = r"/home/pi/documents/past_dl/tr_`date +'%F_%H.%M.%S'`.txt"
	f = open(path, "r")
	text = f.readlines()
	for line in text:
		tc.add_torrent(line)
	f.close()
	# move path file to temp
	call("mv -v {0} {1} ".format(path, destination), shell=True)
# call("mv -v "+path+r" /home/pi/documents/past_dl/tr_`date +'%F_%H.%M.%S'`.txt", shell=True)
else:
	print ('No torrents tonight!')
