#!/bin/bash
filename=$HOME/downloads/yt.txt
TMP=$HOME/tmp
cd $TMP
while read -r line
do
    /usr/local/bin/youtube-dl $line -c
done < "$filename"
mv $TMP/*mp4 $HOME/downloads
mv $filename $HOME/documents/past_dl/yt_`date +'%F_%H.%M.%S'`.txt
