#!/bin/bash
filename=$HOME/downloads/yt.txt
TMP=$HOME/tmp
cd $TMP
while read -r line
do
    /usr/local/bin/youtube-dl $line -cf 271+251/137+140/136+140/247+251/22/18
done < "$filename"
mv -- $TMP/*mp4 $HOME/downloads
mv -- $filename $HOME/documents/past_dl/yt_`date +'%F_%H.%M.%S'`.txt
