#!/bin/bash
# medium quality youtube videos
filename=$HOME/downloads/yt-me.txt
TMP=$HOME/tmp
cd $TMP
while read -r line
do
    /usr/local/bin/youtube-dl -f 18 $line -c
done < "$filename"
mv *mp4 $HOME/videos/mobile
cd -
mv $filename $HOME/documents/past_dl/yt-me_`date +'%F_%H.%M.%S'`.txt
