#!/bin/bash
name=${1%/} # remove trailing slash
comment=$2
#shift 2
#files=$@
files=$name
tarname=${name}_`date +'%F_%H.%M.%S'`_${comment}.tar.gz
backupdir=$HOME/backup/$name
destination=$backupdir/$tarname
if [! -d $backupdir ]; then
  mkdir -p $backupdir
fi
tar czf "$destination" ${files}
