#!/bin/bash
name="$1"
recipient=$2
if [ -f "$name" ]; then
 echo $name | ncat --send-only $recipient 55556
 # https://stackoverflow.com/questions/92802/what-is-the-linux-equivalent-to-dos-pause
 stty -echo
 read -n1 -r -p "Press any key to start transfer..." key
 stty echo
 echo 
 cat "$name" | pv -b | ncat --send-only $recipient 55556
 #cat "$name" | pv -b | netcat $recipient 
else
 echo File "${name}" doesn\'t exist!
 echo D | ncat --send-only $recipient 55556
fi
