#!/bin/bash
name="$1"
recipient=$2
if [ -f "$name" ]; then
 echo $name | ncat --send-only $recipient 55556
 cat "$name" | pv -b | ncat --send-only $recipient 55556
 #cat "$name" | pv -b | netcat $recipient 
else
 echo File "${name}" doesn\'t exist!
 echo 0 | ncat --send-only $recipient 55556
fi
